maintainer       "Emil Soman"
maintainer_email "YOUR_EMAIL"
license          "MIT"
description      "Installs/Configures load_balancer_nginx"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.0"
depends          "application"
depends          "application_ruby"
depends          "application_nginx"
depends          "nginx"
